#==============
# NametagEdit v2.1
#==============
# Development Builds: http://ci.playmc.cc/job/NametagEdit
# Source Code: http://www.github.com/sgtcaze/NametagEdit
#==============

# If enabled, this will remove any formatting created in the tab list by prefixes / suffixes
# Do not set this to true if you already have a plugin that changes the tab list
TabListEnabled: false

# If enabled, this plugin will check for updates when a player with the permission 
# "NametagEdit.update" logs in. Also, the update will check during server startup.
CheckForUpdates: false

# If enabled, this plugin will not print 'Setting prefix/suffix' information in the console
ConsolePrintEnabled: false

# If enabled, this plugin will send small data MCStats.org.
MetricsEnabled: true